### PR TITLE
Documentation: Fix Environment Variables

### PR DESCRIPTION
**Pull request by izzet**
- [x] Fix environment variables defaults in the documentation
- [x] Fix environment variables formatting

### CODE REVIEW

**Review by hariharan-devarajan — APPROVED** [review]
Looks good.

**Comment by hariharan-devarajan** [comment]
Should i merge it?

**Comment by hariharan-devarajan** [comment]
U did a commit after u request for Review.

**Comment by izzet** [comment]
Yes, no more changes 👍🏻

**Pull request merged**
