### PR TITLE
Enhancement: Support for python3 name match for exec and Polaris existing dependency resolution.

### PR DESCRIPTION
**Pull request by hariharan-devarajan**
- [x] The current code strictly looked at Python and did not match Python3. 
- [x] The PR also includes some enhancements for CMake for Polaris to resolve the existing dependencies.

### CODE REVIEW

**Review by rayandrew — APPROVED** [review]
looks good and I have tested it. thanks @hariharan-devarajan

**Comment by rayandrew** [comment]
oh whoops, I got one more issue, now in the generated trace filename, there is no information about the program name especially if we execute the programs with the argument

You can see that it captures `--u` instead of `python3; -u`

I do not know whether you want to fix this, it but it is fine if not as well

image

**Comment by hariharan-devarajan** [comment]
> oh whoops, I got one more issue, now in the generated trace filename, there is no information about the program name especially if we execute the programs with the argument
> 
> You can see that it captures `--u` instead of `python3`
> 
> I do not know whether you want to fix this, it but it is fine if not as well
> 
> image

Ok I ignore names starting from -. Can u try it and let me know.

**Comment by rayandrew** [comment]
Perfect @hariharan-devarajan 

Now, I can get my python filename

image

**Pull request merged**
